# Basic info block
[info]
name = "freebsd-src"
description = "Benchmarking buildworld and buildkernel"

# Specify where to fetch the benchmark's source files, if any
[src.fetch]
url = "https://download.freebsd.org/ftp/releases/amd64/13.1-RELEASE/src.txz"

# Specify how to run the benchmark using make
[run.make]
rootdir = "usr/src"
